### ISSUE TITLE
I would like to see a HOWTO.md 

### ISSUE THREAD

**Issue by infews** [pivotal-sprout/sprout-exemplar#2]
How about a HOWTO that tells me how to use this project? Including how to test drive recipes and providers.

**Comment by aramprice** [comment]
Rough idea, maybe @hiremaga or @wendorf have other thoughts:

---

## How to use

## First Steps

* Copy the contents of `sprout-exemplar` a new directory for your team `sprout-<our-team-name>`
  * Initialize this git repo, maybe add all files so that changes can be tracked?
* Replace all occurrences of `-exemplar` with `-<our-team-name>`
  * Change any filenames containing `exemplar` to `<our-team-name>`
* Test your changes by running `bundle && bundle exec rake`
  * Fix any rubocop, foodcritic, or spec errors

At this point you should have a working sprout-wrap setup with no interesting recipes.

## Second Steps

* Remove `sprout-<our-team-name>::path` recipe (located at `sprout-<our-team-name>/recipes/path.rb`)
* Customize `soloistrc`
  * Add cookbooks
    * [homebrew](https://github.com/chef-cookbooks/homebrew)
     * configure formulas, taps, and casks under the `node_attributes:` key in soloistrc
    * [chruby](https://github.com/pivotal-sprout/sprout-chruby)
    * More resources at [pivotal-sprout](https://github.com/pivotal-sprout)
```

**Comment by aramprice** [comment]
Going to archive this repo, closing.
